### ISSUE TITLE
destroy method

### ISSUE THREAD

**Issue by souporserious** [schne324/live-region#1]
First off, thank you for such a great little plugin! I love this for accessibility. It makes things a little bit easier 😅. I was curious if you would accept a PR for a `destroy` method? I'm using this in a React component and would love to clean things up when the component unmounts.

**Comment by schne324** [comment]
Yea I think a `destroy` method would be great! It should be a rather simple PR

```js
LiveRegion.prototype.destroy = function () {
  this.region.parentNode.removeChild(this.region)
};
```

Don't forget to write a test for it too! :)

**Comment by souporserious** [comment]
Awesome! Done 😄. Thanks for the quick response 🙏. I haven't done a lot of testing before, so hopefully that works ok. I can change whatever, just let me know.

**Comment by schne324** [comment]
Awesome indeed! thanks for the contribution. FYI you can run the tests by executing `npm test`

**Comment by souporserious** [comment]
Not sure what I did wrong, but `npm test` doesn't seem to be working 😕 getting this in the console:
![image](https://user-images.githubusercontent.com/2762082/37494963-5199bb5c-2868-11e8-94f7-8b0bbd18b060.png)

I ran `npm install` before so it should have installed everything 🤔

**Comment by schne324** [comment]
Weird... I'll look into the phantom issue. It's been a while since I originally wrote this - I'm sure some dependencies need updating
