### ISSUE TITLE
can this module be used in electron apps?

### ISSUE THREAD

**Issue by SamKacer** [schne324/live-region#4]
Hello,

I am developing an extension for VS code targeted at creen reader users. I need a way to send messages that are directly read by the screen reader. Can this module be used in this context?

**Comment by schne324** [comment]
As far as I know live regions work within electron apps so I would assume it'd work within the vscode extension context.

**Comment by SamKacer** [comment]
@schne324
aria-live does seem to be working in electron from my little experiment, but I have to create an expensive and overkill webview panel in vs code to create a live region. I am hoping your module could provide a lightweight alternative. here is the code I am trying in my extension:
const LiveRegion = require('live-region');
...
//during extension activation
const live = new LiveRegion();
live.announce('hello world');

I am programming in typescript (not sure if that has an effect). the program fails when I try to  instantiate LiveRegion. I can't find the actual error message, because I am not sure where those are printed in VS code. but when I try to execute the above snippet in node I get the following execution and error:
> const LiveRegion = require('live-region');
undefined
> LiveRegion
[Function: LiveRegion]
> const live = new LiveRegion();
ReferenceError: document is not defined
    at new LiveRegion (c:\workspace\indentflow\node_modules\live-region\index.js:14:17)


the line in index.js of live-region referenced above is 👍 
  this.region = document.createElement('div');


the issue seems to be that you just cant reference document in electron apps.

**Comment by schne324** [comment]
You _can_ access the document using the [`executeJavaScript` method of `webContents`](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsexecutejavascriptcode-usergesture-callback)
